global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'k8s_health_checker'
    static_configs:
      - targets: ['host.docker.internal:8081']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']



